export const DishStub = [
    //Pizza-Pizza Dishes
    {
        category: "Combo",
        dishName: "Meet the Meat Pizzas",
        dishPhoto: "",
        description: "Get both signature Pizza-Pizza dishes for one great price. Comes with one" + 
            "Bacon Cheeseburger Pizza and one Canadian Pizza.",
        review: 5.0,
        price: 20.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Combo",
        dishName: "Appetizer Combo",
        dishPhoto: "",
        description: "Get both Pizza-Pizza appetizers in one big dish. Comes with one order of" + 
            "Jalapeno Poppers and one order of Deep-Fried Pickles.",
        review: 5.0,
        price: 10.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Appetizer",
        dishName: "Jalapeno Poppers",
        dishPhoto: "",
        description: "8 delicious spicy Jalapeno Poppers stuffed with a creamy cheese filling.",
        review: 4.0,
        price: 6.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Appetizer",
        dishName: "Deep-Fried Pickles",
        dishPhoto: "",
        description: "10 classic Deep-Fried Pickles to go with your pizza.",
        review: 4.0,
        price: 6.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Entree",
        dishName: "Bacon Cheeseburger Pizza",
        dishPhoto: "",
        description: "Two food classics mashed together in a pizza topped with ground beef, bacon and a four-cheese blend.",
        review: 5.0,
        price: 15.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Entree",
        dishName: "Canadian Pizza",
        dishPhoto: "",
        description: "Pepperoni, mushrooms and bacon, all on top of our 100% Canadian mozzarella cheese.",
        review: 3.0,
        price: 15.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Dessert",
        dishName: "Cinnamon Sticks",
        dishPhoto: "",
        description: "Strips of funnel cake topped with sugar and cinnamon.",
        review: 3.0,
        price: 6.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Dessert",
        dishName: "Brownie",
        dishPhoto: "",
        description: "A classic brownie for all the chocolate lovers.",
        review: 5.0,
        price: 5.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Drink",
        dishName: "Water",
        dishPhoto: "",
        description: "591 mL bottle of Dasani Water.",
        review: 3.0,
        price: 2.0,
        restaurantName: "Pizza Pizza",
    },
    {
        category: "Drink",
        dishName: "Soda Bottle",
        dishPhoto: "",
        description: "Choose from a variety of 500 mL soda bottles.",
        review: 4.0,
        price: 3.0,
        restaurantName: "Pizza Pizza",
    },
    //Pizza Hut Dishes
    {
        category: "Combo",
        dishName: "The Classic",
        dishPhoto: "",
        description: "The classic pizza dinner, comes with one Supreme Pizza and one basket of our signature Breadsticks.",
        review: 5.0,
        price: 17.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Combo",
        dishName: "The Bread Basket",
        dishPhoto: "",
        description: "If you can't decide on what kind of bread to get, why not get both? Comes with one big basket filled" +
            "with our signature breadsticks and garlic bread.",
        review: 5.0,
        price: 5.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Appetizer",
        dishName: "Breadsticks",
        dishPhoto: "",
        description: "A basket of our signature breadsticks.",
        review: 4.0,
        price: 5.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Appetizer",
        dishName: "Garlic Bread",
        dishPhoto: "",
        description: "Thick pieces of toast brushed with a buttery garlic spread.",
        review: 4.0,
        price: 4.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Entree",
        dishName: "Supreme Pizza",
        dishPhoto: "",
        description: "Comes with all the toppings you need, from sausage and pepperoni to onions and peppers.",
        review: 4.0,
        price: 15.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Entree",
        dishName: "BBQ Chicken Pizza",
        dishPhoto: "",
        description: "BBQ sauce and aged cheddar topped with chicken breast, red onions and green peppers.",
        review: 5.0,
        price: 15.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Dessert",
        dishName: "Cinnamon Rolls",
        dishPhoto: "",
        description: "10 delicious two-bite cinnamon rolls with cream cheese icing.",
        review: 4.0,
        price: 8.0,
        restaurantName: "Pizza Hut",
    },
    {
        category: "Dessert",
        dishName: "Chocolate Chip Cookie",
        dishPhoto: "",
        description: "The ultimate chocolate chip cookie cut into 8 slices for the whole family.",
        review: 5.0,
        price: 8.0,
        restaurantName: "Pizza Hut",
    },
    //Edo Japan Dishes
    {
        category: "Combo",
        dishName: "Kami Platter",
        dishPhoto: "",
        description: "Comes with 3 pieces each of California Rolls, Dynamite Rolls and Salmon Nigiri.",
        review: 5.0,
        price: 13.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Combo",
        dishName: "No Fish Platter",
        dishPhoto: "",
        description: "No raw fish here. Comes with 5 pieces each of California Rolls and Dynamite Rolls.",
        review: 4.0,
        price: 13.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Appetizer",
        dishName: "Tempura Shrimp",
        dishPhoto: "",
        description: "Fresh shrimp coated in our tempura batter and fried to perfection.",
        review: 4.0,
        price: 5.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Appetizer",
        dishName: "Spring Roll",
        dishPhoto: "",
        description: "Delicious chopped vegetables wrapped in a delicate flour shell and fried to perfection.",
        review: 4.0,
        price: 2.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Entree",
        dishName: "California Roll",
        dishPhoto: "",
        description: "Crab mixture, cucumber, avocado, and mayo.",
        review: 3.0,
        price: 5.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Entree",
        dishName: "Dynamite Roll",
        dishPhoto: "",
        description: "Tempura shrimp, cucumber, and avocado.",
        review: 3.0,
        price: 5.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Entree",
        dishName: "Beef Roll",
        dishPhoto: "",
        description: "Beef, cucumber, and avocado.",
        review: 3.0,
        price: 5.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Entree",
        dishName: "Salmon Nigiri",
        dishPhoto: "",
        description: "Rice topped with a salmon fillet.",
        review: 4.0,
        price: 3.0,
        restaurantName: "Edo Japan",
    },
    {
        category: "Dessert",
        dishName: "Chocolate Pocky",
        dishPhoto: "",
        description: "Crispy cookie biscuit stick dipped in dark, chocolate cream.",
        review: 3.0,
        price: 2.0,
        restaurantName: "Edo Japan",
    },
    //Sushi Jet Dishes
    {
        category: "Combo",
        dishName: "Mixed Set A",
        dishPhoto: "",
        description: "Six pieces each of California Maki, Tuna Maki and Salmon Maki.",
        review: 4.0,
        price: 14.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Combo",
        dishName: "Mixed Set B",
        dishPhoto: "",
        description: "Six pieces each of California Maki, Spicy Salmon Maki and Unagi Maki.",
        review: 4.0,
        price: 14.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Appetizer",
        dishName: "Tempura Tofu",
        dishPhoto: "",
        description: "Deep-fried tofu served with tempura sauce.",
        review: 4.0,
        price: 6.0 ,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Appetizer",
        dishName: "Mushroom Butter Yaki",
        dishPhoto: "",
        description: "Pan-fried mushrooms in garlic butter.",
        review: 4.0,
        price: 7.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Entree",
        dishName: "California Maki",
        dishPhoto: "",
        description: "Cucumber, avocado, crab, and tokibo roll.",
        review: 3.0,
        price: 5.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Entree",
        dishName: "Tekka Maki",
        dishPhoto: "",
        description: "Tuna roll.",
        review: 3.0,
        price: 5.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Entree",
        dishName: "Salmon Maki",
        dishPhoto: "",
        description: "Salmon roll.",
        review: 4.0,
        price: 5.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Entree",
        dishName: "Spicy Salmon Maki",
        dishPhoto: "",
        description: "Spicy sauce, salmon, and tempura bits roll.",
        review: 4.0,
        price: 6.0,
        restaurantName: "Sushi Jet",
    },
    {
        category: "Entree",
        dishName: "Unagi Maki",
        dishPhoto: "",
        description: "Eel, avocado, and cucumber roll.",
        review: 3.0,
        price: 6.0,
        restaurantName: "Sushi Jet",
    },
    //McDonalds Dishes
    {
        category: "Combo",
        dishName: "Big Mac Meal",
        dishPhoto: "",
        description: "Comes with a Big Mac, fries and a drink.",
        review: 4.0,
        price: 10.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Combo",
        dishName: "Quarter Pounder Meal",
        dishPhoto: "",
        description: "Comes with a Quarter Pounder, fries and a drink.",
        review: 4.0,
        price: 11.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Appetizer",
        dishName: "French Fries",
        dishPhoto: "",
        description: "McDonald's famous french fries.",
        review: 5.0,
        price: 2.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Appetizer",
        dishName: "Poutine",
        dishPhoto: "",
        description: "McDonald's famous french fries covered in gravy and cheese curds.",
        review: 4.0,
        price: 5.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Entree",
        dishName: "Big Mac",
        dishPhoto: "",
        description: "Comes with lettuce, two patties and our famouse Big Mac Sauce.",
        review: 4.0,
        price: 5.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Entree",
        dishName: "Quarter Pounder",
        dishPhoto: "",
        description: "Our classic quarter pounder comes with cheese, pickles, and onions.",
        review: 4.0,
        price: 6.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Dessert",
        dishName: "Oreo McFlurry",
        dishPhoto: "",
        description: "A delicious ice cream treat filled with chunks of oreos.",
        review: 5.0,
        price: 2.0,
        restaurantName: "McDonalds",
    },
    {
        category: "Dessert",
        dishName: "Baked Apple Pie",
        dishPhoto: "",
        description: "The perfect portion of apple pie for anyone looking for something sweet.",
        review: 4.0,
        price: 1.0,
        restaurantName: "McDonalds",
    },
    //A&W Dishes
    {
        category: "Combo",
        dishName: "Mama Burger Meal",
        dishPhoto: "",
        description: "Comes with a Mama Burger, fries and A&W's signature root beer.",
        review: 4.0,
        price: 10.0,
        restaurantName: "A&W",
    },
    {
        category: "Combo",
        dishName: "Papa Burger Meal",
        dishPhoto: "",
        description: "Comes with a Papa Burger, fries and A&W's signature root beer.",
        review: 4.0,
        price: 12.0,
        restaurantName: "A&W",
    },
    {
        category: "Appetizers",
        dishName: "Onion Rings",
        dishPhoto: "",
        description: "A&W's classic onion rings deep-fried to perfection.",
        review: 5.0,
        price: 4.0,
        restaurantName: "A&W",
    },
    {
        category: "Appetizers",
        dishName: "Thick-Cut Fries",
        dishPhoto: "",
        description: "A&W's signature thick-cut fries made from 100% Canadian grown potatoes.",
        review: 4.0,
        price: 3.0,
        restaurantName: "A&W",
    },
    {
        category: "Entree",
        dishName: "Mama Burger",
        dishPhoto: "",
        description: "A 100% pure beef patty topped with pickles, onion, ketchup, and mustard.",
        review: 5.0,
        price: 5.0,
        restaurantName: "A&W",
    },
    {
        category: "Entree",
        dishName: "Papa Burger",
        dishPhoto: "",
        description: "Two 100% pure beef patties topped with pickles, onion, ketchup, and mustard.",
        review: 5.0,
        price: 7.0,
        restaurantName: "A&W",
    },
    {
        category: "Entree",
        dishName: "Grandpa Burger",
        dishPhoto: "",
        description: "Three 100% pure beef patties topped with pickles, onion, ketchup, and mustard.",
        review: 3.0,
        price: 9.0,
        restaurantName: "A&W",
    },
    {
        category: "Dessert",
        dishName: "Apple Turnover",
        dishPhoto: "",
        description: "Hot apple turnover dusted with cinnamon sugar.",
        review: 4.0,
        price: 1.0,
        restaurantName: "A&W",
    },
    //The Canadian Brewhouse Dishes
    {
        category: "Combo",
        dishName: "Appetizer Mix",
        dishPhoto: "",
        description: "Comes with a mix of Perogies, Dry Ribs, and a bowl of Spinach Dip.",
        review: 5.0,
        price: 30.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Combo",
        dishName: "Wing Mix",
        dishPhoto: "",
        description: "Comes with a 5 lbs platter of both regular and boneless wings.",
        review: 5.0,
        price: 60.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Appetizer",
        dishName: "Perogies",
        dishPhoto: "",
        description: "Cheddar perogies served with sauteed onions, bacon bits, sour cream, and green onions.",
        review: 3.0,
        price: 14.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Appetizer",
        dishName: "Dry Ribs",
        dishPhoto: "",
        description: "Marinated riblets fried and seasoned with sea salt and cracked pepper.",
        review: 3.0,
        price: 14.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Appetizer",
        dishName: "Spinach Dip",
        dishPhoto: "",
        description: "Tri-coloured tortilla chips served with a full bowl of homemade spinach dip.",
        review: 4.0,
        price: 14.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Entree",
        dishName: "Wings",
        dishPhoto: "",
        description: "1 lb of our classic delicious wings.",
        review: 4.0,
        price: 14.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Entree",
        dishName: "Boneless Wings",
        dishPhoto: "",
        description: "1 lb of boneless chicken prepared wing style.",
        review: 3.0,
        price: 14.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Dessert",
        dishName: "Chocolate Cake",
        dishPhoto: "",
        description: "Layers of gooey chocolate over a warm cake served with a scoop of vanilla ice cream.",
        review: 5.0,
        price: 8.0,
        restaurantName: "The Canadian Brewhouse",
    },
    {
        category: "Dessert",
        dishName: "Dessert Poutine",
        dishPhoto: "",
        description: "Donut fries sprinkled with cinnamon and sugar loaded with caramel sauce and chocolate drizzle.",
        review: 4.0,
        price: 8.0,
        restaurantName: "The Canadian Brewhouse",
    },
    //Wild Wings Dishes
    {
        category: "Combo",
        dishName: "Family Bundle",
        dishPhoto: "",
        description: "Comes with 3 lbs of traditional wings, an order of battered mushrooms and an order of garlic cheese bread.",
        review: 5.0,
        price: 60.0,
        restaurantName: "Wild Wings",
    },
    {
        category: "Combo",
        dishName: "Appetizer Combo",
        dishPhoto: "",
        description: "Comes with an order of battered mushrooms and garlic cheese bread.",
        review: 4.0,
        price: 15.0,
        restaurantName: "Wild Wings",
    },
    {
        category: "Appetizer",
        dishName: "Battered Mushrooms",
        dishPhoto: "",
        description: "Lightly battered, deep-fried button mushrooms.",
        review: 3.0,
        price: 10.0,
        restaurantName: "Wild Wings",
    },
    {
        category: "Appetizer",
        dishName: "Garlic Cheese Bread",
        dishPhoto: "",
        description: "Freshly baked loaf smothered in buttery garlic spread.",
        review: 5.0,
        price: 10.0,
        restaurantName: "Wild Wings",
    },
    {
        category: "Entree",
        dishName: "Single Wings",
        dishPhoto: "",
        description: "1 lb of our traditional wings, served with fries, celery, carrots, and dip.",
        review: 4.0,
        price: 18.0 ,
        restaurantName: "Wild Wings",
    },
    {
        category: "Entree",
        dishName: "Triple Wings",
        dishPhoto: "",
        description: "3 lbs of our traditional wings, served with fries, celery, carrots, and dip.",
        review: 4.0,
        price: 40.0,
        restaurantName: "Wild Wings",
    },
    {
        category: "Dessert",
        dishName: "White Chocolate Cheesecake",
        dishPhoto: "",
        description: "Creamy cheesecake swirled with pieces of white chocolate baked on a chocolate crumb.",
        review: 4.0,
        price: 9.0,
        restaurantName: "Wild Wings",
    },
    {
        category: "Dessert",
        dishName: "Oreo Cheesecake",
        dishPhoto: "",
        description: "Oreo cookies baked into a creamy cheesecake topped with a drizzle of chocolate ganache.",
        review: 5.0,
        price: 9.0,
        restaurantName: "Wild Wings",
    }


]