const RestaurantStub = [
  {
    category: "pizza",
    restaurantName: "Pizza Pizza",
    restaurantLogo: "fas fa-utensils fa-5x",
    restaurantImg: "pizza-pizza.png",
    deliveryTime: "20 mins",
    deliveryFee: 5.0,
    review: 3,
  },
  {
    category: "pizza",
    restaurantName: "Pizza Hut",
    restaurantLogo: "fas fa-utensils fa-5x",
    restaurantImg: "pizza-hut.png",
    deliveryTime: "30 mins",
    deliveryFee: 7.0,
    review: 3,
  },
  {
    category: "burger",
    restaurantName: "McDonalds",
    restaurantLogo: "fas fa-store fa-5x",
    restaurantImg: "mcdonalds.png",
    deliveryTime: "10 mins",
    deliveryFee: 2.0,
    review: 3,
  },
  {
    category: "burger",
    restaurantName: "A&W",
    restaurantLogo: "fas fa-store fa-5x",
    restaurantImg: "anw.png",
    deliveryTime: "8 mins",
    deliveryFee: 2.0,
    review: 4,
  },
  {
    category: "sushi",
    restaurantName: "Edo Japan",
    restaurantLogo: "fas fa-store-alt fa-5x",
    restaurantImg: "edo-japan.png",
    deliveryTime: "21 mins",
    deliveryFee: 3.0,
    review: 4,
  },
  {
    category: "sushi",
    restaurantName: "Sushi Jet",
    restaurantLogo: "fas fa-store-alt fa-5x",
    deliveryTime: "29 mins",
    restaurantImg: "sushi-jet.png",
    deliveryFee: 5.0,
    review: 3,
  },
  {
    category: "wings",
    restaurantName: "The Canadian Brewhouse",
    restaurantLogo: "fas fa-utensils fa-5x",
    deliveryTime: "40 mins",
    restaurantImg: "the-canadian-brewhouse.png",
    deliveryFee: 7.0,
    review: 5,
  },
  {
    category: "wings",
    restaurantName: "Wild Wings",
    restaurantLogo: "fas fa-store fa-5x",
    deliveryTime: "25 mins",
    restaurantImg: "wild-wings.png",
    deliveryFee: 5.0,
    review: 4,
  },
  {
    category: "chinese",
    restaurantName: "Asia Palace",
    restaurantLogo: "fas fa-store fa-5x",
    deliveryTime: "22 mins",
    restaurantImg: "asia-palace.png",
    deliveryFee: 4.0,
    review: 3,
  },
  {
    category: "chinese",
    restaurantName: "North Garden",
    restaurantLogo: "fas fa-store-alt fa-5x",
    deliveryTime: "30 mins",
    restaurantImg: "north-garden.png",
    deliveryFee: 5.0,
    review: 4,
  }
];

export default RestaurantStub;