const RestaurantStub = [
  {
    category: "pizza",
    restaurantName: "Pizza Pizza",
    restaurantLogo: "fas fa-utensils fa-5x",
    deliveryTime: "20 mins.",
    deliveryFee: 5.0,
    review: 3,
  },
  {
    category: "pizza",
    restaurantName: "Pizza Hut",
    restaurantLogo: "fas fa-utensils fa-5x",
    deliveryTime: "30 mins.",
    deliveryFee: 7.0,
    review: 3,
  },
  {
    category: "burger",
    restaurantName: "McDonalds",
    restaurantLogo: "fas fa-store fa-5x",
    deliveryTime: "10 mins.",
    deliveryFee: 2.0,
    review: 3,
  },
  {
    category: "burger",
    restaurantName: "A&W",
    restaurantLogo: "fas fa-store fa-5x",
    deliveryTime: "8 mins.",
    deliveryFee: 2.0,
    review: 4,
  },
  {
    category: "sushi",
    restaurantName: "Edo Japan",
    restaurantLogo: "fas fa-store-alt fa-5x",
    deliveryTime: "21 mins.",
    deliveryFee: 3.0,
    review: 4,
  },
  {
    category: "sushi",
    restaurantName: "Sushi Jet",
    restaurantLogo: "fas fa-store-alt fa-5x",
    deliveryTime: "29 mins.",
    deliveryFee: 5.0,
    review: 3,
  },
  {
    category: "wings",
    restaurantName: "The Canadian Brewhouse",
    restaurantLogo: "fas fa-utensils fa-5x",
    deliveryTime: "40 mins.",
    deliveryFee: 7.0,
    review: 5,
  },
  {
    category: "wings",
    restaurantName: "Wild Wings",
    restaurantLogo: "fas fa-store fa-5x",
    deliveryTime: "25 mins.",
    deliveryFee: 5.0,
    review: 4,
  },
  {
    category: "chinese",
    restaurantName: "Asia Palace",
    restaurantLogo: "fas fa-store fa-5x",
    deliveryTime: "22 mins.",
    deliveryFee: 4.0,
    review: 3,
  },
  {
    category: "chinese",
    restaurantName: "North Garden",
    restaurantLogo: "fas fa-store-alt fa-5x",
    deliveryTime: "30 mins.",
    deliveryFee: 5.0,
    review: 4,
  }
];

export default RestaurantStub;
